language: python
python:
    - "2.7"
env:
    - BOARD=uno
    - BOARD=leonardo
    - BOARD=esp01

install:
    - python -c "$(curl -fsSL https://raw.githubusercontent.com/platformio/platformio/master/scripts/get-platformio.py)"

script:
    - cd examples/FullFunction
    - platformio ci -l ../../src FullFunction.ino --board=$BOARD
    - cd ../GetStarted
    - platformio ci -l ../../src GetStarted.ino --board=$BOARD

